services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: registry.digitalocean.com/skz-registry-container/resume-site:latest
    volumes:
      - /root/certs:/etc/nginx/certs
